sudo: required

language: node_js
node_js:
  - 6
  - 7
  - node

matrix:
  allow_failures:
  - node_js: node

services:
  - docker

before_install:
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - bash lambda/test/scripts/aws_credentials.sh
  - make db
  - cd lambda

script:
  - npm test

jobs:
  include:
    - stage: deploy
      if: branch = master
      node_js: 7
      before_install: skip
      script: skip     # usually you do not want to rerun any test
      deploy:
        provider: lambda
        function_name: parliament
        region: eu-west-1
        role: arn:aws:iam::665717792942:role/service-role/parliament
        runtime: nodejs7.10
        handler_name: handler
        access_key_id: AKIAINPNNSVAFWAW5KUQ
        timeout: 60
        zip: lambda
